#!/bin/bash

## #ddev-generated
## Description: run minio client in minio container
## Usage: mc [FLAGS] COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]
## Example: "ddev mc" or "ddev mc ls local"

mc $@
