#!/bin/bash

## Description: Load to an empty postgresql database from .ddev/import-db/postgresql.db.sql
## Usage: pgsql_import
## Example: ddev pgsql_import

# First drop all tables.
su postgres -c "psql -U db -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO db; GRANT ALL ON SCHEMA public TO public;'"

# Import via user postgres to avoid credentials prompt
su postgres -c "psql -U db db < /mnt/ddev_config/import-db/postgresql.db.sql"
