#!/bin/sh

# Run pre-commit check PHP script inside ddev when commiting from host.
if [ "$IS_DDEV_PROJECT" != true ]; then
  ddev exec /usr/bin/php scripts/git/pre-commit.php
else
  /usr/bin/php scripts/git/pre-commit.php
fi
