version: "3.6"
services:
  mysql:
    hostname: ${DDEV_SITENAME}-mysql
    container_name: ddev-${DDEV_SITENAME}-mysql
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    # Versions other than 5.7 should work here.
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306"
    volumes:
      - type: "volume"
        source: mysql-db 
        target: "/var/lib/mysql"
        volume:
          nocopy: true
      - type: "bind"
        source: "."
        target: "/mnt/ddev_config"
    # Optionally send startup flags.
    # command: --sql_mode="" 
# Names our volume
volumes:
  mysql-db:
