version: '3.6'
services:
  cypress:
    image: cypress/included:8.6.0
    container_name: ddev-${DDEV_SITENAME}-cypress
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    user: '$DDEV_UID:$DDEV_GID'
    tty: true
    ipc: host
    links:
      - web:web

    environment:
      - CYPRESS_baseUrl=$DDEV_PRIMARY_URL
      - DISPLAY

    volumes:
      # Mount the project to Cypress's project point
      - "${DDEV_APPROOT}:/e2e"
      # Mount DDEV to allow commands
      - ".:/mnt/ddev_config"
      # Allow X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix

    external_links:
      # Resolve links via DDEV router
      - "ddev-router:${DDEV_HOSTNAME}"

    entrypoint: /bin/bash
    working_dir: /e2e
