version: '3.6'

services:
  sqlsrv:
    container_name: ddev-${DDEV_SITENAME}-sqlsrv
    hostname: ddev-${DDEV_SITENAME}-sqlsrv

    # For possible options: https://hub.docker.com/_/microsoft-mssql-server.
    # This does not yet work with Apple M1. See: https://github.com/microsoft/mssql-docker/issues/734
    image: mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04

    user: root
    volumes:
      - sqlsystem:/var/opt/mssql/
    restart: "no"
    ports:
      - "1433:1433"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:

      # With the following setting you agree with Microsoft's end user license
      # agreement.
      - 'ACCEPT_EULA=Y'

      # The SQL Server enforces password complexity. Trying to set a password
      # that is not sufficiently complex will result in the password not be set.
      # As a result you cannot login with the "SA" user account.
      # The password for the SA account needs to follow the following policy:
      # https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver15
      - 'SA_PASSWORD=Password12!'

      # The following setting is for selecting the SQL Server edition or product
      # key. For possible options:
      # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15
      - 'MSSQL_PID=Evaluation'

      # Sets the default collation for SQL Server. This setting is optional. The
      # current setting is best for Drupal projects. For more information, see:
      # https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15
      - 'MSSQL_COLLATION=LATIN1_GENERAL_100_CI_AS_SC_UTF8'

      # For more possible environment variables that can be set, see:
      # https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver15

  web:
    links:
    - sqlsrv:sqlsrv

volumes:
  sqlsystem:
