version: '3.6'

services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: typo3solr/ext-solr:10.0.1
    restart: "no"
    expose:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
    volumes:
      - "./solr:/opt/solr/server/solr"
      # If you want your solr to persist over `ddev stop` and `ddev start` then uncomment the following line
      # If you uncomment it and want to flush your data you have to `ddev stop` and then
      # `docker volume rm ddev-<projectname>_solrdata` to destroy it.
#      - solr:/var/solr
  web:
    links:
      - solr

volumes:
  # solr is a persistent Docker volume for this project's solr data
  # the volume will be named ddev-<project>_solr
  solr:
