version: '3.6'

services:
  mongo:
    container_name: ddev-${DDEV_SITENAME}-mongo
    image: mongo:4.0
    volumes:
    - type: "volume"
      source: mongo
      target: "/data/db"
      volume:
        nocopy: true
    restart: "no"
    expose:
    - "27017"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
    - MONGO_INITDB_ROOT_USERNAME=db
    - MONGO_INITDB_ROOT_PASSWORD=db
    - MONGO_INITDB_DATABASE=db

  mongo-express:
    container_name: ddev-${DDEV_SITENAME}-mongo-express
    image: mongo-express:0.49
    networks: [default, ddev_default]
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
      com.ddev.platform: ddev
    expose:
    - "8081"
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
      ME_CONFIG_MONGODB_ADMINUSERNAME: db
      ME_CONFIG_MONGODB_ADMINPASSWORD: db
      HTTP_EXPOSE: "8081:8081"

volumes:
  mongo:
