#!/bin/bash

## Description: Downloading data from Platform.sh into DDEV
## Usage: platform-sync [environment]
## Example: "ddev platform-sync" or "ddev platform-sync feature"

# The ID of the project
PLATFORM_PROJECT=

# The ID of the environment
PLATFORM_ENVIRONMENT=develop

if [ "$PLATFORM_PROJECT" != "" ] && [ "$PLATFORM_ENVIRONMENT" != "" ]
then
  # Downloading database
  platform db:dump -p $PLATFORM_PROJECT -e $PLATFORM_ENVIRONMENT -o | ddev import-db

  # Downloading files
  rsync -az `platform ssh -p $PLATFORM_PROJECT -e $PLATFORM_ENVIRONMENT --pipe`:web/sites/default/files web/sites/default/ --verbose
fi

if [ -n "${1:-}" ] ; then
  PLATFORM_ENVIRONMENT="${1}";
fi
