#!/bin/bash

## Description: Run project PHP REPL. Arguments are accepted in Laravel projects (with caveats)
## Usage: tinker
## Example: "ddev tinker"
## Example: "ddev tinker 'User::first()->email'"
## Example: "dev tinker '$node = \Drupal\node\Entity\Node::load(1); print $node->getTitle();'"
## ProjectTypes: laravel,drupal7,drupal8,drupal9,drupal10
## ExecRaw: true

if [ "${DDEV_PROJECT_TYPE}" == "laravel" ]; then
  if [ -z "$1" ]
      then
          php artisan tinker
      else
          php artisan tinker --execute="dd($1);"
  fi

  exit 0
fi

# If this it hit, it's must be a Drupal project type.

if ! command -v drush >/dev/null; then
  echo "drush is not available. You may need to 'ddev composer require drush/drush'"
  exit 1
fi

if [ -z "$1" ]
  then
      drush php
  else
      drush php:eval "$1"
fi
