default:
    suites:
        default:
            contexts:
                - FeatureContext
                - Drupal\DrupalExtension\Context\DrupalContext
                - Drupal\DrupalExtension\Context\MinkContext
                - Drupal\DrupalExtension\Context\MessageContext
                - Drupal\DrupalExtension\Context\DrushContext
    extensions:
        DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
        Drupal\MinkExtension:
            base_url: https://d8.local
            ajax_timeout: 30
            # goutte: ~
            browser_name: chrome
            sessions:
                default:
                    chrome:
                        api_url: "http://chrome:9222"
                        socket_timeout: 20
                        download_behavior: allow
                        validate_certificate: false
        # Using drupalextension "drupal/drupal-extension": "v4.0.0rc1" or above. Use Behat\DrupalExtension if
        Drupal\DrupalExtension:
            drupal:
                # Change this to the absolute path to Drupal install.
                drupal_root: "web"
        Bex\Behat\ScreenshotExtension:
            image_drivers:
                local:
                    screenshot_directory: /var/www/html/behat/results
                    clear_screenshot_directory: true