#!/bin/bash

## Description: Run gulp in theme directory.
## Usage: gulp build|watch
## Example: "ddev gulp", "ddev gulp build", "ddev gulp watch"

## Edit the following line to set the relative path from DDEV_DOCROOT
## to your custom theme root (this example works for Drupal projects.)
THEME=themes/custom/customtheme

## Concatenates path to theme directory for your project.
DDEV_THEMEROOT=/var/www/html/${DDEV_DOCROOT}/${THEME}

## Presupposes that gulp is installed in ${DDEV_THEMEROOT}/node_modules
## You may need to "npm install" theme dependencies before running this.
if [ -d ${DDEV_THEMEROOT} ]
then
  if [ -f ${DDEV_THEMEROOT}/node_modules/gulp/bin/gulp.js ]
  then
    pushd ${DDEV_THEMEROOT}
    ./node_modules/gulp/bin/gulp.js $@
    popd
  else
    echo "Error: No gulp.js found at ./node_modules/gulp/bin/gulp.js."
    echo '(You may need to "npm install" theme dependencies first.)'
  fi
else
  echo "Error: Directory ${DDEV_THEMEROOT} does not exist."
fi
exit

## The same approach should work for other front-end build tools
## (e.g., grunt, brunch, less, sass, compass, etc.)
## which expect to be run with the theme directory as working directory.
## It should also work when building theme assets for WordPress, etc.,
## just by changing the DDEV_THEMEROOT to an appropriate directory.
