#!/bin/bash

## Description: This allows DDEV services activated via docker-compose to be enabled/disabled
## Usage: service [service-name] [status]
## Example: To enable a service: "ddev service postgres enable", "ddev service postgres on"
## Example: To disable a service: "ddev service postgres disable", "ddev service postgres off"


DISABLED_EXT="disabled"
STATUS=null
FILE="./.ddev/docker-compose.$1.yaml"

if [ -f "${FILE}" ]; then
    STATUS="enabled"
fi

if [ -f "${FILE}.${DISABLED_EXT}" ]; then
    STATUS="disabled"
fi

if [ -z "${STATUS}" ]; then
    echo "DDEV '$1' was not detected"
    echo "Are you sure you have ${FILE} file?"
    exit 0
fi

echo "DDEV '$1' service is currently ${STATUS}."

case $2 in
    on|true|enable)
    TARGET="enabled"
    if [ "${STATUS}" = "${TARGET}" ]; then
        echo "Nothing to do"
        exit 0
    fi

    mv "${FILE}.${DISABLED_EXT}" "${FILE}"
    ;;
    off|false|disable)
    TARGET="disabled"
    if [ "${STATUS}" = "${TARGET}" ]; then
        echo "Nothing to do."
        exit 0
    fi

    mv "${FILE}" "${FILE}.${DISABLED_EXT}"
    ;;
    status)
        echo $result
    ;;
    *)
        echo "Invalid argument: $2"
        exit 0;
    ;;
esac

echo "DDEV '$1' has been ${TARGET}."
ddev restart
